image: Visual Studio 2017

cache: C:\Tools\vcpkg\installed\

environment:
  VCPKG_DIR: C:\Tools\vcpkg
  GENERATOR: "Visual Studio 15 2017 Win64"

platform:
  - x64
 
configuration:
  - Release
  - Debug

build:
  parallel: true

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake -G "%GENERATOR%"
          -DCURL_INCLUDE_DIRS="C:\Tools\curl\include"
          -DCURL_LIBRARIES="C:\Tools\curl\bin\libcurl.dll"
          -DCURL_LIBRARY="C:\Tools\curl\bin\libcurl.dll"
          .
  - cmake --build . --config %CONFIGURATION%

after_build:
  - if "%CONFIGURATION%" == "Release" %APPVEYOR_BUILD_FOLDER%\Release\bupcy.exe i -h
  - if "%CONFIGURATION%" == "Release" %APPVEYOR_BUILD_FOLDER%\tests\Release\test_bupcy.exe
