image: Visual Studio 2017

cache: C:\Tools\vcpkg\installed\

environment:
  VCPKG_DIR: C:\Tools\vcpkg
  GENERATOR: "Visual Studio 15 2017 Win64"

platform:
  - x64
 
configuration:
  - Release
  - Debug

init:
  - cd %VCPKG_DIR%
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg version
  - cd %APPVEYOR_BUILD_FOLDER%

install:
  - vcpkg install curl[ssh] --triplet %PLATFORM%-windows
  - vcpkg list

build:
  parallel: true

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake -G "%GENERATOR%"
          -DCMAKE_TOOLCHAIN_FILE="%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake"
          -DCURL_LIBRARIES="%VCPKG_DIR%\installed\%PLATFORM%-windows\lib\libcurl.lib"
          -DCURL_LIBRARY="%VCPKG_DIR%\installed\%PLATFORM%-windows\lib\libcurl.lib"
          .
  - cmake --build . --config %CONFIGURATION%

after_build:
  - if "%CONFIGURATION%" == "Release" %APPVEYOR_BUILD_FOLDER%\Release\bupcy.exe i -h
  - if "%CONFIGURATION%" == "Release" %APPVEYOR_BUILD_FOLDER%\tests\Release\test_bupcy.exe
