sudo: false

language: c 

matrix:
  include:
    - os: linux
      compiler: clang-5.0
      env: COMPILER="CC=clang-5.0"
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - sourceline: 'ppa:jonathonf/curl'
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - clang-5.0
            - cmake-data
            - cmake
            - curl
    - os: linux
      compiler: gcc-7
      env: COMPILER="CC=gcc-7"
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - sourceline: 'ppa:jonathonf/curl'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - cmake-data
            - cmake
            - curl
    - os: osx
      osx_image: xcode9.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "${COMPILER}"; fi

script:
  - ./build.sh
